//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AbstractionReviews struct {
	AbstractionID uuid.UUID `sql:"primary_key"`
	DirectoryID   uuid.UUID `sql:"primary_key"`
	Review        bool
	CreatedOn     time.Time
	LastUpdatedOn time.Time
}
