//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type Catalogue struct {
	ID              uuid.UUID `sql:"primary_key"`
	ProjectID       uuid.UUID
	DirectoryID     uuid.UUID
	Name            string
	Description     string
	Catalogue       pq.StringArray
	CreatedOn       time.Time
	LastUpdatedOn   time.Time
	CanPublicView   bool
	CatalogueVector string `json:"-"`
}
