//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type DirectoryIam struct {
	DirectoryID          uuid.UUID `sql:"primary_key"`
	Email                *string
	Password             *string `json:"-"`
	IsEmailVerified      bool
	DirectoryIamTicketID *string
	TicketNumber         *string `json:"-"`
	Pin                  *string `json:"-"`
	CreatedOn            time.Time
	LastUpdatedOn        time.Time
}
