//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type DirectoryProjectsRoles struct {
	DirectoryID   uuid.UUID `sql:"primary_key"`
	ProjectID     uuid.UUID `sql:"primary_key"`
	ProjectRoleID string    `sql:"primary_key"`
	CreatedOn     time.Time
}
