//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PlatformStatistics struct {
	NoOfProjects       *int64
	NoOfModelTemplates *int64
	NoOfCatalogues     *int64
	NoOfAbstractions   *int64
}
