version: "3.8"

services:
  postgres16:
    image: postgres:16
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres2023
      POSTGRES_DB: postgres
  pgadmin7.6:
    image: dpage/pgadmin4:7.6
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: siscokcherono@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  redis7.2:
    image: redis:7.2-rc-bookworm
    restart: always
    ports:
      - "6379:6379"
  redisinsight1.14.0:
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "6380:8001"
