//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DirectoryIamTicketTypes = newDirectoryIamTicketTypesTable("public", "directory_iam_ticket_types", "")

type directoryIamTicketTypesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type DirectoryIamTicketTypesTable struct {
	directoryIamTicketTypesTable

	EXCLUDED directoryIamTicketTypesTable
}

// AS creates new DirectoryIamTicketTypesTable with assigned alias
func (a DirectoryIamTicketTypesTable) AS(alias string) *DirectoryIamTicketTypesTable {
	return newDirectoryIamTicketTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DirectoryIamTicketTypesTable with assigned schema name
func (a DirectoryIamTicketTypesTable) FromSchema(schemaName string) *DirectoryIamTicketTypesTable {
	return newDirectoryIamTicketTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DirectoryIamTicketTypesTable with assigned table prefix
func (a DirectoryIamTicketTypesTable) WithPrefix(prefix string) *DirectoryIamTicketTypesTable {
	return newDirectoryIamTicketTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DirectoryIamTicketTypesTable with assigned table suffix
func (a DirectoryIamTicketTypesTable) WithSuffix(suffix string) *DirectoryIamTicketTypesTable {
	return newDirectoryIamTicketTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDirectoryIamTicketTypesTable(schemaName, tableName, alias string) *DirectoryIamTicketTypesTable {
	return &DirectoryIamTicketTypesTable{
		directoryIamTicketTypesTable: newDirectoryIamTicketTypesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newDirectoryIamTicketTypesTableImpl("", "excluded", ""),
	}
}

func newDirectoryIamTicketTypesTableImpl(schemaName, tableName, alias string) directoryIamTicketTypesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		DescriptionColumn = postgres.StringColumn("description")
		allColumns        = postgres.ColumnList{IDColumn, DescriptionColumn}
		mutableColumns    = postgres.ColumnList{DescriptionColumn}
	)

	return directoryIamTicketTypesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
