//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Projects = newProjectsTable("public", "projects", "")

type projectsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	DirectoryID    postgres.ColumnString
	Name           postgres.ColumnString
	Description    postgres.ColumnString
	CreatedOn      postgres.ColumnTimestampz
	LastUpdatedOn  postgres.ColumnTimestampz
	IsActive       postgres.ColumnBool
	ProjectsVector postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ProjectsTable struct {
	projectsTable

	EXCLUDED projectsTable
}

// AS creates new ProjectsTable with assigned alias
func (a ProjectsTable) AS(alias string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProjectsTable with assigned schema name
func (a ProjectsTable) FromSchema(schemaName string) *ProjectsTable {
	return newProjectsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProjectsTable with assigned table prefix
func (a ProjectsTable) WithPrefix(prefix string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProjectsTable with assigned table suffix
func (a ProjectsTable) WithSuffix(suffix string) *ProjectsTable {
	return newProjectsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProjectsTable(schemaName, tableName, alias string) *ProjectsTable {
	return &ProjectsTable{
		projectsTable: newProjectsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newProjectsTableImpl("", "excluded", ""),
	}
}

func newProjectsTableImpl(schemaName, tableName, alias string) projectsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		DirectoryIDColumn    = postgres.StringColumn("directory_id")
		NameColumn           = postgres.StringColumn("name")
		DescriptionColumn    = postgres.StringColumn("description")
		CreatedOnColumn      = postgres.TimestampzColumn("created_on")
		LastUpdatedOnColumn  = postgres.TimestampzColumn("last_updated_on")
		IsActiveColumn       = postgres.BoolColumn("is_active")
		ProjectsVectorColumn = postgres.StringColumn("projects_vector")
		allColumns           = postgres.ColumnList{IDColumn, DirectoryIDColumn, NameColumn, DescriptionColumn, CreatedOnColumn, LastUpdatedOnColumn, IsActiveColumn, ProjectsVectorColumn}
		mutableColumns       = postgres.ColumnList{DirectoryIDColumn, NameColumn, DescriptionColumn, CreatedOnColumn, LastUpdatedOnColumn, IsActiveColumn, ProjectsVectorColumn}
	)

	return projectsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		DirectoryID:    DirectoryIDColumn,
		Name:           NameColumn,
		Description:    DescriptionColumn,
		CreatedOn:      CreatedOnColumn,
		LastUpdatedOn:  LastUpdatedOnColumn,
		IsActive:       IsActiveColumn,
		ProjectsVector: ProjectsVectorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
