//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ProjectRoles = newProjectRolesTable("public", "project_roles", "")

type projectRolesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ProjectRolesTable struct {
	projectRolesTable

	EXCLUDED projectRolesTable
}

// AS creates new ProjectRolesTable with assigned alias
func (a ProjectRolesTable) AS(alias string) *ProjectRolesTable {
	return newProjectRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProjectRolesTable with assigned schema name
func (a ProjectRolesTable) FromSchema(schemaName string) *ProjectRolesTable {
	return newProjectRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProjectRolesTable with assigned table prefix
func (a ProjectRolesTable) WithPrefix(prefix string) *ProjectRolesTable {
	return newProjectRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProjectRolesTable with assigned table suffix
func (a ProjectRolesTable) WithSuffix(suffix string) *ProjectRolesTable {
	return newProjectRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProjectRolesTable(schemaName, tableName, alias string) *ProjectRolesTable {
	return &ProjectRolesTable{
		projectRolesTable: newProjectRolesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newProjectRolesTableImpl("", "excluded", ""),
	}
}

func newProjectRolesTableImpl(schemaName, tableName, alias string) projectRolesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		DescriptionColumn = postgres.StringColumn("description")
		allColumns        = postgres.ColumnList{IDColumn, DescriptionColumn}
		mutableColumns    = postgres.ColumnList{DescriptionColumn}
	)

	return projectRolesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
