//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AbstractionReviews = AbstractionReviews.FromSchema(schema)
	AbstractionReviewsComments = AbstractionReviewsComments.FromSchema(schema)
	Abstractions = Abstractions.FromSchema(schema)
	Catalogue = Catalogue.FromSchema(schema)
	Directory = Directory.FromSchema(schema)
	DirectoryIam = DirectoryIam.FromSchema(schema)
	DirectoryIamTicketTypes = DirectoryIamTicketTypes.FromSchema(schema)
	DirectoryProjectsRoles = DirectoryProjectsRoles.FromSchema(schema)
	DirectorySystemUsers = DirectorySystemUsers.FromSchema(schema)
	Files = Files.FromSchema(schema)
	ModelTemplates = ModelTemplates.FromSchema(schema)
	ProjectRoles = ProjectRoles.FromSchema(schema)
	Projects = Projects.FromSchema(schema)
	Storage = Storage.FromSchema(schema)
	StorageProjects = StorageProjects.FromSchema(schema)
	StorageTypes = StorageTypes.FromSchema(schema)
}
